<?php
include_once './common/class.common.inc';
//include_once 'blade/view.reg_payment.blade.inc';
?>
<div class="panel panel-default">
	<div class="panel-heading">Registration Payment</div>
	<div class="panel-body">
		<h1 class="hh1"> KHULNA UNIVERSITY </h1>
		<h2 class="hh1" id="hh2"> Students Payment Receipt </h2>
		<div class="aa">
		Student Name:			<br>
		Discipline:
		Roll No:<br>
		Term:
		Year:
		</div>    
</div>
<form method="post"></form>

<table>
    <tr>
        <td>
            <input type="text" name="company" form="my_form" />
            <button type="button" form="my_form">ok</button>
        </td>
    </tr>
</table>